const cfg=window.APP_CONFIG, app=document.querySelector('#app');
if(!cfg?.supabaseUrl||!cfg?.supabaseAnonKey)throw Error('أكمل config.js');
const db=window.supabase.createClient(cfg.supabaseUrl,cfg.supabaseAnonKey),S={user:null,profile:null,ws:null,folder:null,query:'',view:'grid'};
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const size=n=>n<1048576?`${Math.ceil(n/1024)} KB`:`${(n/1048576).toFixed(1)} MB`, date=d=>new Intl.DateTimeFormat('ar-SA',{dateStyle:'medium'}).format(new Date(d));
async function get(p){const{data,error}=await p;if(error)throw error;return data}async function rpc(f,a={}){return get(db.rpc(f,a))}const icon=m=>m?.includes('pdf')?'📕':m?.includes('sheet')||m?.includes('excel')?'📊':m?.includes('image')?'🖼️':m?.includes('zip')?'🗜️':'📄';
function toast(x,bad=false){const t=document.querySelector('#toast');t.textContent=x;t.className=`show ${bad?'error':''}`;clearTimeout(window.tm);window.tm=setTimeout(()=>t.className='',3500)}
async function run(fn){try{document.body.classList.add('loading');return await fn()}catch(e){console.error(e);toast(e.message||'تعذرت العملية',true)}finally{document.body.classList.remove('loading')}}
function modal(title,html){document.body.insertAdjacentHTML('beforeend',`<div class="modal" id="modal"><section class="dialog"><header><h2>${esc(title)}</h2><button class="iconBtn" onclick="closeModal()">×</button></header>${html}</section></div>`)}function closeModal(){document.querySelector('#modal')?.remove()}
function auth(){app.innerHTML=`<section class="authLayout"><div class="authIntro"><i>◫</i><h1>مساحات الشركة</h1><p>منصة داخلية آمنة للملفات والفرق والصلاحيات.</p><div>✓ ملفات محمية &nbsp; ✓ تعاون سريع &nbsp; ✓ سجل نشاط</div></div><form class="authCard" onsubmit="signIn(event)"><p class="eyebrow">أهلاً بك</p><h2>تسجيل الدخول</h2><label>البريد الإلكتروني<input id="email" class="field" type="email" required></label><label>كلمة المرور<input id="password" class="field" type="password" required></label><button class="btn primary full">دخول</button><hr><h3>حساب جديد</h3><label>الاسم الكامل<input id="fullName" class="field" minlength="2"></label><button type="button" class="btn secondary full" onclick="signUp()">إنشاء الحساب</button></form></section>`}
function shell(body){app.innerHTML=`<div class="shell"><aside class="side"><b class="brand">◫ مساحات الشركة</b><button onclick="dashboard()">▦ لوحة التحكم</button><button onclick="employees()">♙ الموظفون</button><button onclick="invitations()">✉ الدعوات</button><span></span><small>${esc(S.profile?.full_name)}</small><button onclick="logout()">↪ تسجيل الخروج</button></aside><main class="main">${body}</main></div>`}
const empty=(t,p,a='')=>`<div class="empty"><i>◫</i><h3>${t}</h3><p>${p}</p>${a?`<button class="btn primary" onclick="${a}">ابدأ الآن</button>`:''}</div>`;
async function dashboard(){await run(async()=>{S.ws=null;const spaces=await rpc('workspace_summaries');shell(`<header class="pageHeader"><div><p class="eyebrow">لوحة التحكم</p><h1>مرحبًا ${esc(S.profile.full_name)} 👋</h1><p>مساحاتك وملفاتك المشتركة في مكان واحد.</p></div><button class="btn primary" onclick="newWorkspace()">＋ مساحة عمل</button></header><div class="statGrid"><article><b>${spaces.length}</b><small>مساحة عمل</small></article><article><b>${spaces.reduce((a,x)=>a+Number(x.file_count||0),0)}</b><small>ملف</small></article><article><b>${spaces.reduce((a,x)=>a+Number(x.member_count||0),0)}</b><small>عضوية</small></article></div><h2>مساحات العمل</h2><section class="spaceGrid">${spaces.map(w=>`<button class="spaceCard" onclick="openWorkspace('${w.id}')"><i>${esc(w.name[0])}</i><h3>${esc(w.name)}</h3><p>${esc(w.description||'مساحة عمل مشتركة')}</p><footer>♙ ${w.member_count} أعضاء <span>⌁ ${w.file_count} ملفات</span></footer></button>`).join('')||empty('لا توجد مساحات','أنشئ أول مساحة عمل للبدء.','newWorkspace()')}</section>`)} )}
function newWorkspace(){modal('مساحة عمل جديدة',`<form onsubmit="saveWorkspace(event)"><label>الاسم<input id="wsName" class="field" minlength="2" required></label><label>الوصف<textarea id="wsDesc" class="field" placeholder="اختياري"></textarea></label><footer><button type="button" class="btn secondary" onclick="closeModal()">إلغاء</button><button class="btn primary">إنشاء</button></footer></form>`)}async function saveWorkspace(e){e.preventDefault();await run(async()=>{const w=await rpc('create_workspace',{workspace_name:wsName.value.trim(),workspace_description:wsDesc.value.trim()||null});closeModal();toast('تم إنشاء مساحة العمل');openWorkspace(w.id)})}
async function openWorkspace(id,folder=null){await run(async()=>{S.ws=await rpc('workspace_detail',{workspace_id:id,folder_id:folder});S.folder=folder;S.query='';renderFiles()})}
async function renderFiles(){const w=S.ws,role=w.my_role,write=['owner','admin','editor'].includes(role),admin=['owner','admin'].includes(role);const d=await rpc('workspace_items',{workspace_id:w.id,parent_folder_id:S.folder,search_text:S.query||null});shell(`<div class="crumb"><button onclick="dashboard()">لوحة التحكم</button> / <b>${esc(w.name)}</b></div><header class="pageHeader"><div><h1>${esc(w.name)}</h1><p>${esc(w.description||'مساحة عمل مشتركة')} <em>${role}</em></p></div><div class="actions">${write?'<button class="btn secondary" onclick="newFolder()">＋ مجلد</button><button class="btn primary" onclick="filePicker.click()">↑ رفع ملف</button>':''}${admin?'<button class="btn secondary" onclick="members()">♙ أعضاء</button>':''}<button class="btn secondary" onclick="activity()">◷ النشاط</button></div></header><input id="filePicker" type="file" hidden onchange="upload(this.files[0])"><div class="fileControls"><input class="search" placeholder="⌕ ابحث في الملفات والمجلدات" oninput="search(this.value)"><div><button onclick="setView('grid')">▦</button><button onclick="setView('table')">☷</button></div></div>${S.folder?'<button class="back" onclick="openWorkspace(S.ws.id,null)">← المجلد الرئيسي</button>':''}<section class="items ${S.view}">${d.folders.map(f=>`<article class="item"><button class="itemName" onclick="openWorkspace(S.ws.id,'${f.id}')">📁 <b>${esc(f.name)}</b></button><small>مجلد · ${date(f.updated_at)}</small>${write?`<button class="dots" onclick="menu('folder','${f.id}','${esc(f.name)}')">⋮</button>`:''}</article>`).join('')}${d.files.map(f=>`<article class="item"><button class="itemName" onclick="fileDetail('${f.id}')">${icon(f.mime_type)} <b>${esc(f.name)}</b></button><small>${size(f.size_bytes)} · ${esc(f.uploader_name||'')}</small>${write?`<button class="dots" onclick="menu('file','${f.id}','${esc(f.name)}')">⋮</button>`:''}</article>`).join('')||empty(S.query?'لا توجد نتائج':'هذا المجلد فارغ',S.query?'جرّب بحثًا آخر.':'ارفع ملفًا أو أنشئ مجلدًا.')}</section><section class="memberStrip"><b>الأعضاء (${w.members.length})</b><div>${w.members.map(m=>`<i title="${esc(m.full_name)}">${esc(m.full_name[0])}</i>`).join('')}</div></section>`)}
let timer;function search(x){clearTimeout(timer);timer=setTimeout(()=>{S.query=x;renderFiles()},250)}function setView(v){S.view=v;renderFiles()}
function newFolder(){modal('مجلد جديد',`<form onsubmit="saveFolder(event)"><input id="folderName" class="field" required maxlength="160" placeholder="اسم المجلد"><footer><button class="btn primary">إنشاء</button></footer></form>`)}async function saveFolder(e){e.preventDefault();await run(async()=>{await rpc('create_folder',{workspace_id:S.ws.id,parent_folder_id:S.folder,folder_name:folderName.value});closeModal();renderFiles()})}
async function upload(file){if(!file)return;if(file.size>25*1024*1024)return toast('الحد الأعلى 25MB',true);const path=`${S.ws.id}/${crypto.randomUUID()}`;await run(async()=>{await get(db.storage.from('workspace-files').upload(path,file,{contentType:file.type||'application/octet-stream'}));try{await rpc('create_file_record',{workspace_id:S.ws.id,parent_folder_id:S.folder,file_name:file.name,file_type:file.type||'application/octet-stream',file_size:file.size,file_path:path})}catch(e){await db.storage.from('workspace-files').remove([path]);throw e}toast('تم رفع الملف');renderFiles()})}
async function fileDetail(id){await run(async()=>{const f=await rpc('file_detail',{file_id:id});modal(f.name,`<div class="preview">${icon(f.mime_type)}<h3>${esc(f.name)}</h3><p>${size(f.size_bytes)} · ${esc(f.uploader_name)}</p><button class="btn primary" onclick="download('${f.storage_path}','${esc(f.name)}')">↓ تنزيل</button></div>`)})}async function download(path,name){await run(async()=>{const b=await get(db.storage.from('workspace-files').download(path));const a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)})}
function menu(kind,id,name){modal(name,`<div class="menu"><button onclick="rename('${kind}','${id}','${name}')">✎ إعادة تسمية</button><button class="dangerText" onclick="removeItem('${kind}','${id}','${name}')">⌫ حذف</button></div>`)}async function rename(kind,id,name){closeModal();const n=prompt('الاسم الجديد',name);if(!n||n===name)return;await run(async()=>{await rpc('rename_workspace_item',{item_type:kind,item_id:id,new_name:n});renderFiles()})}async function removeItem(kind,id,name){
  closeModal();

  if(!confirm(`حذف ${name}؟`)) return;

  await run(async()=>{
    if(kind === 'file'){
      const file = await rpc('file_detail',{file_id:id});

      if(file?.storage_path){
        await get(
          db.storage
            .from('workspace-files')
            .remove([file.storage_path])
        );
      }
    }

    await rpc('delete_workspace_item',{
      item_type:kind,
      item_id:id
    });

    toast('تم الحذف');
    renderFiles();
  });
}
async function members(){await run(async()=>{modal('أعضاء مساحة العمل',`<div class="memberList">${S.ws.members.map(m=>`<article><i>${esc(m.full_name[0])}</i><div><b>${esc(m.full_name)}</b><small>${esc(m.email)}</small></div><span>${m.role}</span></article>`).join('')}</div><button class="btn primary full" onclick="invite()">＋ دعوة موظف</button>`)})}async function invite(){const p=await rpc('available_profiles',{workspace_id:S.ws.id});modal('دعوة موظف',`<form onsubmit="sendInvite(event)"><select id="inviteUser" class="field">${p.map(x=>`<option value="${x.id}">${esc(x.full_name)} — ${esc(x.email)}</option>`).join('')}</select><select id="inviteRole" class="field"><option value="viewer">Viewer</option><option value="editor">Editor</option><option value="admin">Admin</option></select><button class="btn primary">إرسال الدعوة</button></form>`)}async function sendInvite(e){e.preventDefault();await run(async()=>{await rpc('send_invitation',{workspace_id:S.ws.id,recipient_id:inviteUser.value,member_role:inviteRole.value});closeModal();toast('تم إرسال الدعوة')})}
async function invitations(){await run(async()=>{const x=await rpc('my_pending_invitations');shell(`<header class="pageHeader"><div><p class="eyebrow">الدعوات</p><h1>دعوات الانضمام</h1></div></header><section class="list">${x.map(i=>`<article><i>${esc(i.workspace_name[0])}</i><div><b>${esc(i.workspace_name)}</b><small>من ${esc(i.sender_name)} · ${i.role}</small></div><button class="btn primary" onclick="accept('${i.id}')">قبول</button><button class="btn secondary" onclick="decline('${i.id}')">رفض</button></article>`).join('')||empty('لا توجد دعوات','ستظهر الدعوات هنا.')}</section>`)})}async function accept(id){await run(async()=>{await rpc('accept_invitation',{invitation_id:id});dashboard()})}async function decline(id){await run(async()=>{await rpc('decline_invitation',{invitation_id:id});invitations()})}
async function employees(){await run(async()=>{const p=await rpc('company_profiles');shell(`<header class="pageHeader"><div><p class="eyebrow">دليل الشركة</p><h1>الموظفون</h1></div></header><section class="employeeGrid">${p.map(x=>`<article><i>${esc(x.full_name[0])}</i><div><b>${esc(x.full_name)}</b><small>${esc(x.email)}</small></div></article>`).join('')}</section>`)})}async function activity(){await run(async()=>{const x=await rpc('workspace_activity',{workspace_id:S.ws.id});modal('سجل النشاط',`<div class="timeline">${x.map(a=>`<article><i>${esc(a.actor_name[0])}</i><p><b>${esc(a.actor_name)}</b> ${esc(a.action)} ${esc(a.entity_name)}<small>${date(a.created_at)}</small></p></article>`).join('')}</div>`)})}
async function signIn(e){e.preventDefault();await run(async()=>{await get(db.auth.signInWithPassword({email:email.value,password:password.value}));boot()})}async function signUp(){await run(async()=>{if(!fullName.value||fullName.value.length<2)throw Error('أدخل الاسم الكامل');const d=await get(db.auth.signUp({email:email.value,password:password.value,options:{data:{full_name:fullName.value}}}));if(d.session)boot();else toast('تحقق من بريدك الإلكتروني لتأكيد الحساب')})}async function logout(){await db.auth.signOut();auth()}async function boot(){await run(async()=>{const{data:{user}}=await db.auth.getUser();if(!user)return auth();S.user=user;S.profile=await rpc('my_profile');dashboard()})}
Object.assign(window,{signIn,signUp,dashboard,newWorkspace,saveWorkspace,closeModal,openWorkspace,search,setView,newFolder,saveFolder,upload,fileDetail,download,menu,rename,removeItem,members,invite,sendInvite,invitations,accept,decline,employees,activity,logout});boot();
