/* نظام المهام: يعتمد على دوال RPC المعرفة في supabase/upgrade_v3_tasks.sql */
const T=()=>window.APP;
const statusLabel={todo:'جديدة',in_progress:'قيد التنفيذ',done:'مكتملة'};
const priorityLabel={low:'منخفضة',medium:'متوسطة',high:'عالية'};
function taskCard(x){const a=T();return `<article class="taskCard priority-${x.priority}" onclick="taskDetail('${x.id}')"><div class="taskCardTop"><span class="priorityDot ${x.priority}"></span><small>${a.esc(x.workspace_name)}</small><button onclick="event.stopPropagation();taskStatus('${x.id}','${x.status}')" class="status ${x.status}">${statusLabel[x.status]}</button></div><h3>${a.esc(x.title)}</h3><p>${a.esc(x.description||'لا يوجد وصف')}</p><footer><span>⚑ ${priorityLabel[x.priority]}</span><span>${x.due_date?`◷ ${x.due_date}`:'بدون موعد'}</span><span>♙ ${x.assignee_count}</span></footer></article>`}
async function tasks(){const a=T();await a.run(async()=>{const x=await a.rpc('my_tasks');a.shell(`<header class="pageHeader"><div><p class="eyebrow">إدارة العمل</p><h1>المهام</h1><p>تابع ما أُسند إليك وما أنشأته في مساحات العمل.</p></div><button class="btn primary" onclick="newTask()">＋ مهمة جديدة</button></header><section class="taskStats"><article><b>${x.filter(t=>t.status==='todo').length}</b><small>جديدة</small></article><article><b>${x.filter(t=>t.status==='in_progress').length}</b><small>قيد التنفيذ</small></article><article><b>${x.filter(t=>t.status==='done').length}</b><small>مكتملة</small></article></section><section class="taskBoard"><div><h2>جديدة <span>${x.filter(t=>t.status==='todo').length}</span></h2>${x.filter(t=>t.status==='todo').map(taskCard).join('')||'<p class="taskEmpty">لا توجد مهام</p>'}</div><div><h2>قيد التنفيذ <span>${x.filter(t=>t.status==='in_progress').length}</span></h2>${x.filter(t=>t.status==='in_progress').map(taskCard).join('')||'<p class="taskEmpty">لا توجد مهام</p>'}</div><div><h2>مكتملة <span>${x.filter(t=>t.status==='done').length}</span></h2>${x.filter(t=>t.status==='done').map(taskCard).join('')||'<p class="taskEmpty">لا توجد مهام</p>'}</div></section>`)} )}
async function newTask(){const a=T();const spaces=await a.rpc('workspace_summaries');if(!spaces.length)return a.toast('أنشئ مساحة عمل أولًا',true);a.modal('مهمة جديدة',`<form onsubmit="saveTask(event)"><label>مساحة العمل<select id="taskWorkspace" class="field">${spaces.map(s=>`<option value="${s.id}">${a.esc(s.name)}</option>`).join('')}</select></label><label>عنوان المهمة<input id="taskTitle" class="field" required maxlength="180" placeholder="مثال: مراجعة تقرير الجرد"></label><label>الوصف<textarea id="taskDescription" class="field" maxlength="3000" placeholder="التفاصيل والخطوات المطلوبة"></textarea></label><div class="twoFields"><label>الأولوية<select id="taskPriority" class="field"><option value="low">منخفضة</option><option value="medium" selected>متوسطة</option><option value="high">عالية</option></select></label><label>تاريخ الاستحقاق<input id="taskDue" class="field" type="date"></label></div><footer><button type="button" class="btn secondary" onclick="closeModal()">إلغاء</button><button class="btn primary">إنشاء المهمة</button></footer></form>`)}
async function saveTask(e){e.preventDefault();const a=T();await a.run(async()=>{const task=await a.rpc('create_task',{workspace_id:taskWorkspace.value,task_title:taskTitle.value.trim(),task_description:taskDescription.value.trim()||null,task_priority:taskPriority.value,task_due_date:taskDue.value||null});a.closeModal();a.toast('تم إنشاء المهمة');taskDetail(task.id)})}
async function taskDetail(id){const a=T();await a.run(async()=>{const t=await a.rpc('task_detail',{task_id:id});a.modal(t.title,`<div class="taskDetail"><div class="taskMeta"><span class="status ${t.status}">${statusLabel[t.status]}</span><span>⚑ ${priorityLabel[t.priority]}</span><span>◷ ${t.due_date||'بدون موعد'}</span></div><p class="taskDescription">${a.esc(t.description||'لا يوجد وصف لهذه المهمة.')}</p><section><h3>المسند إليهم</h3><div class="assignees">${t.assignees.map(x=>`<span>${a.esc(x.full_name)}</span>`).join('')||'<span class="muted">لم تُسند لأي موظف بعد</span>'}</div><button class="btn secondary" onclick="assignTask('${t.id}')">＋ إسناد موظف</button></section><section><h3>التعليقات</h3><div class="comments">${t.comments.map(c=>`<article><b>${a.esc(c.author_name)}</b><p>${a.esc(c.body)}</p><small>${a.date(c.created_at)}</small></article>`).join('')||'<p class="muted">لا توجد تعليقات بعد.</p>'}</div><form onsubmit="addComment(event,'${t.id}')"><input id="commentBody" class="field" required maxlength="1500" placeholder="اكتب تحديثًا أو تعليقًا…"><button class="btn primary">إرسال</button></form></section><footer><button class="btn secondary" onclick="taskStatus('${t.id}','${t.status}')">تغيير الحالة</button></footer></div>`)} )}
async function taskStatus(id,current){const a=T();const next=current==='todo'?'in_progress':current==='in_progress'?'done':'todo';await a.run(async()=>{await a.rpc('update_task_status',{task_id:id,new_status:next});a.toast(`تم نقل المهمة إلى: ${statusLabel[next]}`);tasks()})}
async function assignTask(id){const a=T();const p=await a.rpc('task_available_assignees',{task_id:id});a.modal('إسناد المهمة',`<form onsubmit="saveAssignee(event,'${id}')"><select id="assigneeId" class="field">${p.map(x=>`<option value="${x.id}">${a.esc(x.full_name)} — ${a.esc(x.email)}</option>`).join('')}</select><footer><button class="btn primary">إسناد</button></footer></form>`)}async function saveAssignee(e,id){e.preventDefault();const a=T();await a.run(async()=>{await a.rpc('assign_task',{task_id:id,assignee_id:assigneeId.value});a.closeModal();a.toast('تم إسناد المهمة');taskDetail(id)})}
async function addComment(e,id){e.preventDefault();const a=T();await a.run(async()=>{await a.rpc('add_task_comment',{task_id:id,comment_body:commentBody.value.trim()});taskDetail(id)})}
Object.assign(window,{tasks,newTask,saveTask,taskDetail,taskStatus,assignTask,saveAssignee,addComment});
