/* مهام مساحات الشركة: مرفقات، قوائم إنجاز، وتعليقات. */
const T=()=>window.APP;
const statusLabel={todo:'جديدة',in_progress:'قيد التنفيذ',done:'مكتملة'};
const priorityLabel={low:'منخفضة',medium:'متوسطة',high:'عالية'};
let taskFilter='all',taskSearch='';
const taskSafeName=n=>n.replace(/[^\w.\-\u0600-\u06ff ]/g,'_').slice(0,140);
function taskCard(x){const a=T(),pct=x.checklist_count?Math.round(100*x.checklist_done/x.checklist_count):0;return `<article class="taskCard priority-${x.priority}" onclick="taskDetail('${x.id}')"><div class="taskCardTop"><span class="priorityDot ${x.priority}"></span><small>${a.esc(x.workspace_name)}</small><button title="نقل للحالة التالية" onclick="event.stopPropagation();taskStatus('${x.id}','${x.status}')" class="status ${x.status}">${statusLabel[x.status]}</button></div><h3>${a.esc(x.title)}</h3><p>${a.esc(x.description||'لا يوجد وصف')}</p>${x.checklist_count?`<div class="taskProgress"><i style="width:${pct}%"></i></div><small class="progressText">${x.checklist_done}/${x.checklist_count} عناصر مكتملة</small>`:''}<footer><span>⚑ ${priorityLabel[x.priority]}</span><span>${x.due_date?`◷ ${x.due_date}`:'بدون موعد'}</span><span>📎 ${x.attachment_count}</span><span>♙ ${x.assignee_count}</span></footer></article>`}
async function tasks(){const a=T();await a.run(async()=>{const all=await a.rpc('my_tasks');let x=all;if(taskFilter!=='all')x=x.filter(t=>t.status===taskFilter);if(taskSearch)x=x.filter(t=>`${t.title} ${t.workspace_name}`.toLowerCase().includes(taskSearch.toLowerCase()));a.shell(`<header class="pageHeader"><div><p class="eyebrow">إدارة العمل</p><h1>مركز المهام</h1><p>أنشئ المهام، أرسلها للفريق، وأرفق الملفات وتابع الإنجاز من مكان واحد.</p></div><button class="btn primary" onclick="newTask()">＋ مهمة جديدة</button></header><section class="taskStats"><article><b>${all.filter(t=>t.status==='todo').length}</b><small>جديدة</small></article><article><b>${all.filter(t=>t.status==='in_progress').length}</b><small>قيد التنفيذ</small></article><article><b>${all.filter(t=>t.status==='done').length}</b><small>مكتملة</small></article></section><section class="taskTools"><input class="field" value="${a.esc(taskSearch)}" oninput="taskSearch=this.value;tasks()" placeholder="ابحث عن مهمة أو مساحة عمل…"><div>${['all','todo','in_progress','done'].map(s=>`<button class="filter ${taskFilter===s?'active':''}" onclick="taskFilter='${s}';tasks()">${s==='all'?'الكل':statusLabel[s]}</button>`).join('')}</div></section><section class="taskBoard"><div><h2>جديدة <span>${x.filter(t=>t.status==='todo').length}</span></h2>${x.filter(t=>t.status==='todo').map(taskCard).join('')||'<p class="taskEmpty">لا توجد مهام</p>'}</div><div><h2>قيد التنفيذ <span>${x.filter(t=>t.status==='in_progress').length}</span></h2>${x.filter(t=>t.status==='in_progress').map(taskCard).join('')||'<p class="taskEmpty">لا توجد مهام</p>'}</div><div><h2>مكتملة <span>${x.filter(t=>t.status==='done').length}</span></h2>${x.filter(t=>t.status==='done').map(taskCard).join('')||'<p class="taskEmpty">لا توجد مهام</p>'}</div></section>`)} )}
async function newTask(){const a=T(),spaces=await a.rpc('workspace_summaries');if(!spaces.length)return a.toast('أنشئ مساحة عمل أولًا',true);a.modal('مهمة جديدة',`<form onsubmit="saveTask(event)"><label>مساحة العمل<select id="taskWorkspace" class="field">${spaces.map(s=>`<option value="${s.id}">${a.esc(s.name)}</option>`).join('')}</select></label><label>عنوان المهمة<input id="taskTitle" class="field" required maxlength="180" placeholder="مثال: مراجعة تقرير الجرد"></label><label>الوصف<textarea id="taskDescription" class="field" maxlength="3000" placeholder="التفاصيل والخطوات المطلوبة"></textarea></label><div class="twoFields"><label>الأولوية<select id="taskPriority" class="field"><option value="low">منخفضة</option><option value="medium" selected>متوسطة</option><option value="high">عالية</option></select></label><label>تاريخ الاستحقاق<input id="taskDue" class="field" type="date"></label></div><footer><button type="button" class="btn secondary" onclick="closeModal()">إلغاء</button><button class="btn primary">إنشاء المهمة</button></footer></form>`)}
async function saveTask(e){e.preventDefault();const a=T();await a.run(async()=>{const task=await a.rpc('create_task',{p_workspace_id:taskWorkspace.value,p_task_title:taskTitle.value.trim(),p_task_description:taskDescription.value.trim()||null,p_task_priority:taskPriority.value,p_task_due_date:taskDue.value||null});a.closeModal();a.toast('تم إنشاء المهمة');taskDetail(task.id)})}
function attachmentRow(x,id){const a=T();return `<li><button onclick="openTaskAttachment('${x.storage_path}')">📎 ${a.esc(x.file_name)} <small>${Math.ceil(x.size/1024)} KB</small></button><button class="iconDanger" title="حذف المرفق" onclick="removeTaskAttachment('${x.id}','${id}','${x.storage_path}')">×</button></li>`}
async function taskDetail(id){const a=T();await a.run(async()=>{const t=await a.rpc('task_detail',{p_task_id:id});if(!t)return a.toast('المهمة غير موجودة أو لا تملك صلاحية الوصول',true);const done=t.checklist.filter(x=>x.is_done).length,pct=t.checklist.length?Math.round(done*100/t.checklist.length):0;a.modal(t.title,`<div class="taskDetail"><div class="taskMeta"><span class="status ${t.status}">${statusLabel[t.status]}</span><span>⚑ ${priorityLabel[t.priority]}</span><span>◷ ${t.due_date||'بدون موعد'}</span></div><p class="taskDescription">${a.esc(t.description||'لا يوجد وصف لهذه المهمة.')}</p><section><div class="sectionTitle"><h3>قائمة الإنجاز</h3><b>${pct}%</b></div><div class="taskProgress big"><i style="width:${pct}%"></i></div><div class="checklist">${t.checklist.map(x=>`<label><input type="checkbox" ${x.is_done?'checked':''} onchange="toggleChecklist('${x.id}','${id}')"><span>${a.esc(x.title)}</span></label>`).join('')||'<p class="muted">أضف خطوات صغيرة لتتابع تقدم المهمة.</p>'}</div><form onsubmit="addChecklist(event,'${id}')"><input id="checklistTitle" class="field" required maxlength="220" placeholder="أضف خطوة أو بندًا…"><button class="btn secondary">إضافة</button></form></section><section><h3>المرفقات</h3><ul class="attachments">${t.attachments.map(x=>attachmentRow(x,id)).join('')||'<li class="muted">لا توجد ملفات مرفقة.</li>'}</ul><label class="uploadTask"><input id="taskAttachmentInput" type="file" onchange="uploadTaskFile('${id}')">📎 أرفق ملفًا للمهمة <small>حتى 25 MB</small></label></section><section><h3>المسند إليهم</h3><div class="assignees">${t.assignees.map(x=>`<span>${a.esc(x.full_name)}</span>`).join('')||'<span class="muted">لم تُسند لأي موظف بعد</span>'}</div><button class="btn secondary" onclick="assignTask('${t.id}')">＋ إسناد موظف</button></section><section><h3>التعليقات والتحديثات</h3><div class="comments">${t.comments.map(c=>`<article><b>${a.esc(c.author_name)}</b><p>${a.esc(c.body)}</p><small>${a.date(c.created_at)}</small></article>`).join('')||'<p class="muted">لا توجد تعليقات بعد.</p>'}</div><form onsubmit="addComment(event,'${t.id}')"><input id="commentBody" class="field" required maxlength="1500" placeholder="اكتب تحديثًا أو تعليقًا…"><button class="btn primary">إرسال</button></form></section><footer><button class="btn secondary" onclick="taskStatus('${t.id}','${t.status}')">تغيير الحالة</button></footer></div>`)} )}
async function taskStatus(id,current){const a=T(),next=current==='todo'?'in_progress':current==='in_progress'?'done':'todo';await a.run(async()=>{await a.rpc('update_task_status',{p_task_id:id,p_new_status:next});a.toast(`تم نقل المهمة إلى: ${statusLabel[next]}`);taskDetail(id);tasks()})}
async function assignTask(id){const a=T(),p=await a.rpc('task_available_assignees',{p_task_id:id});a.modal('إسناد المهمة',`<form onsubmit="saveAssignee(event,'${id}')"><select id="assigneeId" class="field">${p.map(x=>`<option value="${x.id}">${a.esc(x.full_name)} — ${a.esc(x.email)}</option>`).join('')}</select><footer><button class="btn primary">إسناد</button></footer></form>`)}
async function saveAssignee(e,id){e.preventDefault();const a=T();await a.run(async()=>{await a.rpc('assign_task',{p_task_id:id,p_assignee_id:assigneeId.value});a.closeModal();a.toast('تم إسناد المهمة');taskDetail(id)})}
async function addComment(e,id){e.preventDefault();const a=T();await a.run(async()=>{await a.rpc('add_task_comment',{p_task_id:id,p_comment_body:commentBody.value.trim()});taskDetail(id)})}
async function addChecklist(e,id){e.preventDefault();const a=T();await a.run(async()=>{await a.rpc('add_task_checklist_item',{p_task_id:id,p_title:checklistTitle.value.trim()});taskDetail(id)})}
async function toggleChecklist(item,id){const a=T();await a.run(async()=>{await a.rpc('toggle_task_checklist_item',{p_item_id:item});taskDetail(id)})}
async function uploadTaskFile(id){const a=T(),file=document.getElementById('taskAttachmentInput')?.files?.[0];if(!file)return;if(file.size>25*1024*1024)return a.toast('الحد الأقصى للمرفق 25 MB',true);await a.run(async()=>{const key=`${id}/${crypto.randomUUID()}-${taskSafeName(file.name)}`,up=await a.db.storage.from('task-files').upload(key,file,{contentType:file.type||'application/octet-stream',upsert:false});if(up.error)throw up.error;try{await a.rpc('create_task_attachment',{p_task_id:id,p_file_name:file.name,p_storage_path:key,p_size:file.size,p_mime_type:file.type||'application/octet-stream'})}catch(err){await a.db.storage.from('task-files').remove([key]);throw err}a.toast('تم إرفاق الملف');taskDetail(id)})}
async function openTaskAttachment(path){const a=T();await a.run(async()=>{const r=await a.db.storage.from('task-files').createSignedUrl(path,120);if(r.error)throw r.error;window.open(r.data.signedUrl,'_blank','noopener')})}
async function removeTaskAttachment(attachment,id,path){const a=T();if(!confirm('حذف هذا المرفق؟'))return;await a.run(async()=>{const r=await a.db.storage.from('task-files').remove([path]);if(r.error)throw r.error;await a.rpc('delete_task_attachment',{p_attachment_id:attachment});a.toast('تم حذف المرفق');taskDetail(id)})}
Object.assign(window,{tasks,newTask,saveTask,taskDetail,taskStatus,assignTask,saveAssignee,addComment,addChecklist,toggleChecklist,uploadTaskFile,openTaskAttachment,removeTaskAttachment});
